### ISSUE TITLE
Euler to Quaternion constrution

### ISSUE THREAD

**Issue by coltcorrea** [jpreiss/cmath3d#1]
Your library is great but it seems to be missing one thing.  I am using an embedded processor connected to a Gyro and Acclerometer to calculate rotation.  I get the Euler Angular Velocities from the Gyro and need to update my Euler angles based on that.

while(true)
{
1. rpyvect (initial) -> "rpytoquat" (seems missing)
2. Rotate Quat with your "quat_gyro_update"
3. Convert back to Euler with your "quat2rpy"
4. Use updated rpyvect
}

Can you create a rpytoquat function for this purpose?

**Comment by jpreiss** [comment]
I can create this function, but I'm curious why you are using Euler angles as your core representation of the attitude, rather than just using a quaternion? You can always convert the quaternion to Euler angles when needed.

**Comment by jpreiss** [comment]
rpy2quat added in 0a51824cee952ba3902d0fcc1c5407d359707a1a. Note that rpy2quat and quat2rpy are copied from [the wikipedia page](https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles) and thus use the same Euler angle conventions illustrated there.

**Comment by coltcorrea** [comment]
Thanks for your comments.  Actually we do use the quats for our main work but since the Gyro delivers rpy, we need to init our quats with the gyro data.  This is the reason to construct the quats with rpy.
